#This is typically used to manage secrets from external systems like
#AWS Secrets Manager, Azure Key Vault, or HashiCorp Vault, using the ExternalSecrets operator.
#The operator fetches secrets from these external providers
#and injects them into Kubernetes as native Secret resources.

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-externalsecret
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: {{ .Values.externalSecret.creationPolicy | default "Owner" }}
  data:
    - secretKey: db-username
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.dbUsernameKey }}
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.dbPasswordKey }}
