apiVersion: apps/v1
kind: Deployment
metadata:
  name: naga-{{ .Release.Revision }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: naga-{{ .Release.Revision }}
  template:
    metadata:
      labels:
        app: naga-{{ .Release.Revision }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MY_ENV_VAR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: myKey

