apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-externalsecret
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secret
  data:
    - secretKey: my-secret-key
      remoteRef:
        key: {{ .Values.externalSecret.key }}