on:
  workflow_call:

  push:
    branches:
      - main
      - 'releases/**'

permissions:
  checks: write
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: "${{ vars.AWS_ASSUME_ROLE }}"
          aws-region: "${{ vars.AWS_REGION }}"

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2.0.1
        env:
          AWS_ASSUME_ROLE: "${{ vars.AWS_ASSUME_ROLE }}"
          AWS_REGION: "${{ vars.AWS_REGION }}"
        with:
          mask-password: 'false'
          registry-type: private

      - name: Set Helm Application Version
        id: set-version
        run: |
          # Extract the version dynamically, for example from a Chart.yaml file or git tag
          VERSION=$(cat charts/application/Chart.yaml | grep '^version:' | awk '{print $2}')
          echo "VERSION=${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Package and push helm chart to Amazon ECR
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: charts/application
          VERSION: ${{ env.version }}
        run: |
          helm package $REPOSITORY
          helm push helm-application-${VERSION}.tgz oci://$REGISTRY