name: Push Helm Chart to ECR and Kubernetes

on:
  workflow_call:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: "0.1.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Change this to your AWS region

      - name: Login to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | helm registry login -u AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Package Helm Chart
        env:
          VERSION: ${{ env.VERSION }}
          run: |
            helm package naga-chart --version $VERSION
            mv naga-chart-$VERSION.tgz my-chart.tgz

      - name: Push Helm Chart to ECR
        run: |
          helm push naga-chart-$VERSION.tgz oci://${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}
